<?php

return [
    'currencies' => [
        ['id' => 1, 'name' => 'US Dollar', 'code' => 'USD', 'symbol' => '$', 'is_default' => true],
        ['id' => 2, 'name' => 'Euro', 'code' => 'EUR', 'symbol' => '€', 'is_default' => false],
        ['id' => 3, 'name' => 'British Pound', 'code' => 'GBP', 'symbol' => '£', 'is_default' => false],
        ['id' => 4, 'name' => 'Japanese Yen', 'code' => 'JPY', 'symbol' => '¥', 'is_default' => false],
        ['id' => 5, 'name' => 'Canadian Dollar', 'code' => 'CAD', 'symbol' => 'C$', 'is_default' => false],
        ['id' => 6, 'name' => 'Australian Dollar', 'code' => 'AUD', 'symbol' => 'A$', 'is_default' => false],
        ['id' => 7, 'name' => 'Swiss Franc', 'code' => 'CHF', 'symbol' => 'CHF', 'is_default' => false],
        ['id' => 8, 'name' => 'Chinese Yuan', 'code' => 'CNY', 'symbol' => '¥', 'is_default' => false],
        ['id' => 9, 'name' => 'Indian Rupee', 'code' => 'INR', 'symbol' => '₹', 'is_default' => false],
        ['id' => 10, 'name' => 'South Korean Won', 'code' => 'KRW', 'symbol' => '₩', 'is_default' => false],
        ['id' => 11, 'name' => 'Mexican Peso', 'code' => 'MXN', 'symbol' => '$', 'is_default' => false],
        ['id' => 12, 'name' => 'Brazilian Real', 'code' => 'BRL', 'symbol' => 'R$', 'is_default' => false],
        ['id' => 13, 'name' => 'Russian Ruble', 'code' => 'RUB', 'symbol' => '₽', 'is_default' => false],
        ['id' => 14, 'name' => 'South African Rand', 'code' => 'ZAR', 'symbol' => 'R', 'is_default' => false],
        ['id' => 15, 'name' => 'Singapore Dollar', 'code' => 'SGD', 'symbol' => 'S$', 'is_default' => false],
        ['id' => 16, 'name' => 'Hong Kong Dollar', 'code' => 'HKD', 'symbol' => 'HK$', 'is_default' => false],
        ['id' => 17, 'name' => 'Norwegian Krone', 'code' => 'NOK', 'symbol' => 'kr', 'is_default' => false],
        ['id' => 18, 'name' => 'Swedish Krona', 'code' => 'SEK', 'symbol' => 'kr', 'is_default' => false],
        ['id' => 19, 'name' => 'Danish Krone', 'code' => 'DKK', 'symbol' => 'kr', 'is_default' => false],
        ['id' => 20, 'name' => 'Polish Zloty', 'code' => 'PLN', 'symbol' => 'zł', 'is_default' => false],
        ['id' => 21, 'name' => 'Turkish Lira', 'code' => 'TRY', 'symbol' => '₺', 'is_default' => false],
        ['id' => 22, 'name' => 'Thai Baht', 'code' => 'THB', 'symbol' => '฿', 'is_default' => false],
        ['id' => 23, 'name' => 'New Zealand Dollar', 'code' => 'NZD', 'symbol' => 'NZ$', 'is_default' => false],
        ['id' => 24, 'name' => 'Israeli Shekel', 'code' => 'ILS', 'symbol' => '₪', 'is_default' => false],
        ['id' => 25, 'name' => 'UAE Dirham', 'code' => 'AED', 'symbol' => 'د.إ', 'is_default' => false],
        ['id' => 26, 'name' => 'Saudi Riyal', 'code' => 'SAR', 'symbol' => '﷼', 'is_default' => false],
        ['id' => 27, 'name' => 'Egyptian Pound', 'code' => 'EGP', 'symbol' => '£', 'is_default' => false],
        ['id' => 28, 'name' => 'Nigerian Naira', 'code' => 'NGN', 'symbol' => '₦', 'is_default' => false],
        ['id' => 29, 'name' => 'Kenyan Shilling', 'code' => 'KES', 'symbol' => 'KSh', 'is_default' => false],
        ['id' => 30, 'name' => 'Philippine Peso', 'code' => 'PHP', 'symbol' => '₱', 'is_default' => false],
        ['id' => 31, 'name' => 'Afghan Afghani', 'code' => 'AFN', 'symbol' => '؋', 'is_default' => false],
        ['id' => 32, 'name' => 'Albanian Lek', 'code' => 'ALL', 'symbol' => 'L', 'is_default' => false],
        ['id' => 33, 'name' => 'Algerian Dinar', 'code' => 'DZD', 'symbol' => 'د.ج', 'is_default' => false],
        ['id' => 34, 'name' => 'Angolan Kwanza', 'code' => 'AOA', 'symbol' => 'Kz', 'is_default' => false],
        ['id' => 35, 'name' => 'Argentine Peso', 'code' => 'ARS', 'symbol' => '$', 'is_default' => false],
        ['id' => 36, 'name' => 'Armenian Dram', 'code' => 'AMD', 'symbol' => '֏', 'is_default' => false],
        ['id' => 37, 'name' => 'Aruban Florin', 'code' => 'AWG', 'symbol' => 'ƒ', 'is_default' => false],
        ['id' => 38, 'name' => 'Azerbaijani Manat', 'code' => 'AZN', 'symbol' => '₼', 'is_default' => false],
        ['id' => 39, 'name' => 'Bahamian Dollar', 'code' => 'BSD', 'symbol' => '$', 'is_default' => false],
        ['id' => 40, 'name' => 'Bahraini Dinar', 'code' => 'BHD', 'symbol' => '.د.ب', 'is_default' => false],
        ['id' => 41, 'name' => 'Bangladeshi Taka', 'code' => 'BDT', 'symbol' => '৳', 'is_default' => false],
        ['id' => 42, 'name' => 'Barbadian Dollar', 'code' => 'BBD', 'symbol' => '$', 'is_default' => false],
        ['id' => 43, 'name' => 'Belarusian Ruble', 'code' => 'BYN', 'symbol' => 'Br', 'is_default' => false],
        ['id' => 44, 'name' => 'Belize Dollar', 'code' => 'BZD', 'symbol' => '$', 'is_default' => false],
        ['id' => 45, 'name' => 'Bermudian Dollar', 'code' => 'BMD', 'symbol' => '$', 'is_default' => false],
        ['id' => 46, 'name' => 'Bhutanese Ngultrum', 'code' => 'BTN', 'symbol' => 'Nu.', 'is_default' => false],
        ['id' => 47, 'name' => 'Bolivian Boliviano', 'code' => 'BOB', 'symbol' => 'Bs.', 'is_default' => false],
        ['id' => 48, 'name' => 'Bosnia-Herzegovina Convertible Mark', 'code' => 'BAM', 'symbol' => 'KM', 'is_default' => false],
        ['id' => 49, 'name' => 'Botswanan Pula', 'code' => 'BWP', 'symbol' => 'P', 'is_default' => false],
        ['id' => 50, 'name' => 'Brunei Dollar', 'code' => 'BND', 'symbol' => '$', 'is_default' => false],
        ['id' => 51, 'name' => 'Bulgarian Lev', 'code' => 'BGN', 'symbol' => 'лв', 'is_default' => false],
        ['id' => 52, 'name' => 'Burundian Franc', 'code' => 'BIF', 'symbol' => 'Fr', 'is_default' => false],
        ['id' => 53, 'name' => 'Cambodian Riel', 'code' => 'KHR', 'symbol' => '៛', 'is_default' => false],
        ['id' => 54, 'name' => 'Cape Verdean Escudo', 'code' => 'CVE', 'symbol' => '$', 'is_default' => false],
        ['id' => 55, 'name' => 'Cayman Islands Dollar', 'code' => 'KYD', 'symbol' => '$', 'is_default' => false],
        ['id' => 56, 'name' => 'Central African CFA Franc', 'code' => 'XAF', 'symbol' => 'Fr', 'is_default' => false],
        ['id' => 57, 'name' => 'CFP Franc', 'code' => 'XPF', 'symbol' => 'Fr', 'is_default' => false],
        ['id' => 58, 'name' => 'Chilean Peso', 'code' => 'CLP', 'symbol' => '$', 'is_default' => false],
        ['id' => 59, 'name' => 'Colombian Peso', 'code' => 'COP', 'symbol' => '$', 'is_default' => false],
        ['id' => 60, 'name' => 'Comorian Franc', 'code' => 'KMF', 'symbol' => 'Fr', 'is_default' => false],
        ['id' => 61, 'name' => 'Congolese Franc', 'code' => 'CDF', 'symbol' => 'Fr', 'is_default' => false],
        ['id' => 62, 'name' => 'Costa Rican Colón', 'code' => 'CRC', 'symbol' => '₡', 'is_default' => false],
        ['id' => 63, 'name' => 'Croatian Kuna', 'code' => 'HRK', 'symbol' => 'kn', 'is_default' => false],
        ['id' => 64, 'name' => 'Cuban Peso', 'code' => 'CUP', 'symbol' => '$', 'is_default' => false],
        ['id' => 65, 'name' => 'Czech Koruna', 'code' => 'CZK', 'symbol' => 'Kč', 'is_default' => false],
        ['id' => 66, 'name' => 'Djiboutian Franc', 'code' => 'DJF', 'symbol' => 'Fr', 'is_default' => false],
        ['id' => 67, 'name' => 'Dominican Peso', 'code' => 'DOP', 'symbol' => '$', 'is_default' => false],
        ['id' => 68, 'name' => 'East Caribbean Dollar', 'code' => 'XCD', 'symbol' => '$', 'is_default' => false],
        ['id' => 69, 'name' => 'Eritrean Nakfa', 'code' => 'ERN', 'symbol' => 'Nfk', 'is_default' => false],
        ['id' => 70, 'name' => 'Ethiopian Birr', 'code' => 'ETB', 'symbol' => 'Br', 'is_default' => false],
        ['id' => 71, 'name' => 'Falkland Islands Pound', 'code' => 'FKP', 'symbol' => '£', 'is_default' => false],
        ['id' => 72, 'name' => 'Faroese Króna', 'code' => 'FOK', 'symbol' => 'kr', 'is_default' => false],
        ['id' => 73, 'name' => 'Fijian Dollar', 'code' => 'FJD', 'symbol' => '$', 'is_default' => false],
        ['id' => 74, 'name' => 'Gambian Dalasi', 'code' => 'GMD', 'symbol' => 'D', 'is_default' => false],
        ['id' => 75, 'name' => 'Georgian Lari', 'code' => 'GEL', 'symbol' => '₾', 'is_default' => false],
        ['id' => 76, 'name' => 'Ghanaian Cedi', 'code' => 'GHS', 'symbol' => '₵', 'is_default' => false],
        ['id' => 77, 'name' => 'Gibraltar Pound', 'code' => 'GIP', 'symbol' => '£', 'is_default' => false],
        ['id' => 78, 'name' => 'Guatemalan Quetzal', 'code' => 'GTQ', 'symbol' => 'Q', 'is_default' => false],
        ['id' => 79, 'name' => 'Guinean Franc', 'code' => 'GNF', 'symbol' => 'Fr', 'is_default' => false],
        ['id' => 80, 'name' => 'Guyanaese Dollar', 'code' => 'GYD', 'symbol' => '$', 'is_default' => false],
        ['id' => 81, 'name' => 'Haitian Gourde', 'code' => 'HTG', 'symbol' => 'G', 'is_default' => false],
        ['id' => 82, 'name' => 'Honduran Lempira', 'code' => 'HNL', 'symbol' => 'L', 'is_default' => false],
        ['id' => 83, 'name' => 'Hungarian Forint', 'code' => 'HUF', 'symbol' => 'Ft', 'is_default' => false],
        ['id' => 84, 'name' => 'Icelandic Króna', 'code' => 'ISK', 'symbol' => 'kr', 'is_default' => false],
        ['id' => 85, 'name' => 'Indonesian Rupiah', 'code' => 'IDR', 'symbol' => 'Rp', 'is_default' => false],
        ['id' => 86, 'name' => 'Iranian Rial', 'code' => 'IRR', 'symbol' => '﷼', 'is_default' => false],
        ['id' => 87, 'name' => 'Iraqi Dinar', 'code' => 'IQD', 'symbol' => 'ع.د', 'is_default' => false],
        ['id' => 88, 'name' => 'Jamaican Dollar', 'code' => 'JMD', 'symbol' => '$', 'is_default' => false],
        ['id' => 89, 'name' => 'Jordanian Dinar', 'code' => 'JOD', 'symbol' => 'د.ا', 'is_default' => false],
        ['id' => 90, 'name' => 'Kazakhstani Tenge', 'code' => 'KZT', 'symbol' => '₸', 'is_default' => false],
        ['id' => 91, 'name' => 'Kuwaiti Dinar', 'code' => 'KWD', 'symbol' => 'د.ك', 'is_default' => false],
        ['id' => 92, 'name' => 'Kyrgystani Som', 'code' => 'KGS', 'symbol' => 'с', 'is_default' => false],
        ['id' => 93, 'name' => 'Laotian Kip', 'code' => 'LAK', 'symbol' => '₭', 'is_default' => false],
        ['id' => 94, 'name' => 'Lebanese Pound', 'code' => 'LBP', 'symbol' => 'ل.ل', 'is_default' => false],
        ['id' => 95, 'name' => 'Lesotho Loti', 'code' => 'LSL', 'symbol' => 'L', 'is_default' => false],
        ['id' => 96, 'name' => 'Liberian Dollar', 'code' => 'LRD', 'symbol' => '$', 'is_default' => false],
        ['id' => 97, 'name' => 'Libyan Dinar', 'code' => 'LYD', 'symbol' => 'ل.د', 'is_default' => false],
        ['id' => 98, 'name' => 'Macanese Pataca', 'code' => 'MOP', 'symbol' => 'P', 'is_default' => false],
        ['id' => 99, 'name' => 'Macedonian Denar', 'code' => 'MKD', 'symbol' => 'ден', 'is_default' => false],
        ['id' => 100, 'name' => 'Malagasy Ariary', 'code' => 'MGA', 'symbol' => 'Ar', 'is_default' => false],
        ['id' => 101, 'name' => 'Malawian Kwacha', 'code' => 'MWK', 'symbol' => 'MK', 'is_default' => false],
        ['id' => 102, 'name' => 'Malaysian Ringgit', 'code' => 'MYR', 'symbol' => 'RM', 'is_default' => false],
        ['id' => 103, 'name' => 'Maldivian Rufiyaa', 'code' => 'MVR', 'symbol' => '.ރ', 'is_default' => false],
        ['id' => 104, 'name' => 'Mauritanian Ouguiya', 'code' => 'MRU', 'symbol' => 'UM', 'is_default' => false],
        ['id' => 105, 'name' => 'Mauritian Rupee', 'code' => 'MUR', 'symbol' => '₨', 'is_default' => false],
        ['id' => 106, 'name' => 'Moldovan Leu', 'code' => 'MDL', 'symbol' => 'L', 'is_default' => false],
        ['id' => 107, 'name' => 'Mongolian Tugrik', 'code' => 'MNT', 'symbol' => '₮', 'is_default' => false],
        ['id' => 108, 'name' => 'Moroccan Dirham', 'code' => 'MAD', 'symbol' => 'د.م.', 'is_default' => false],
        ['id' => 109, 'name' => 'Mozambican Metical', 'code' => 'MZN', 'symbol' => 'MT', 'is_default' => false],
        ['id' => 110, 'name' => 'Myanmar Kyat', 'code' => 'MMK', 'symbol' => 'Ks', 'is_default' => false],
        ['id' => 111, 'name' => 'Namibian Dollar', 'code' => 'NAD', 'symbol' => '$', 'is_default' => false],
        ['id' => 112, 'name' => 'Nepalese Rupee', 'code' => 'NPR', 'symbol' => '₨', 'is_default' => false],
        ['id' => 113, 'name' => 'Netherlands Antillean Guilder', 'code' => 'ANG', 'symbol' => 'ƒ', 'is_default' => false],
        ['id' => 114, 'name' => 'Nicaraguan Córdoba', 'code' => 'NIO', 'symbol' => 'C$', 'is_default' => false],
        ['id' => 115, 'name' => 'North Korean Won', 'code' => 'KPW', 'symbol' => '₩', 'is_default' => false],
        ['id' => 116, 'name' => 'Omani Rial', 'code' => 'OMR', 'symbol' => 'ر.ع.', 'is_default' => false],
        ['id' => 117, 'name' => 'Pakistani Rupee', 'code' => 'PKR', 'symbol' => '₨', 'is_default' => false],
        ['id' => 118, 'name' => 'Panamanian Balboa', 'code' => 'PAB', 'symbol' => 'B/.', 'is_default' => false],
        ['id' => 119, 'name' => 'Papua New Guinean Kina', 'code' => 'PGK', 'symbol' => 'K', 'is_default' => false],
        ['id' => 120, 'name' => 'Paraguayan Guarani', 'code' => 'PYG', 'symbol' => '₲', 'is_default' => false],
        ['id' => 121, 'name' => 'Peruvian Nuevo Sol', 'code' => 'PEN', 'symbol' => 'S/.', 'is_default' => false],
        ['id' => 122, 'name' => 'Qatari Rial', 'code' => 'QAR', 'symbol' => 'ر.ق', 'is_default' => false],
        ['id' => 123, 'name' => 'Romanian Leu', 'code' => 'RON', 'symbol' => 'lei', 'is_default' => false],
        ['id' => 124, 'name' => 'Rwandan Franc', 'code' => 'RWF', 'symbol' => 'Fr', 'is_default' => false],
        ['id' => 125, 'name' => 'Saint Helena Pound', 'code' => 'SHP', 'symbol' => '£', 'is_default' => false],
        ['id' => 126, 'name' => 'Samoan Tala', 'code' => 'WST', 'symbol' => 'T', 'is_default' => false],
        ['id' => 127, 'name' => 'São Tomé and Príncipe Dobra', 'code' => 'STN', 'symbol' => 'Db', 'is_default' => false],
        ['id' => 128, 'name' => 'Serbian Dinar', 'code' => 'RSD', 'symbol' => 'дин.', 'is_default' => false],
        ['id' => 129, 'name' => 'Seychellois Rupee', 'code' => 'SCR', 'symbol' => '₨', 'is_default' => false],
        ['id' => 130, 'name' => 'Sierra Leonean Leone', 'code' => 'SLL', 'symbol' => 'Le', 'is_default' => false],
        ['id' => 131, 'name' => 'Solomon Islands Dollar', 'code' => 'SBD', 'symbol' => '$', 'is_default' => false],
        ['id' => 132, 'name' => 'Somali Shilling', 'code' => 'SOS', 'symbol' => 'Sh', 'is_default' => false],
        ['id' => 133, 'name' => 'Sri Lankan Rupee', 'code' => 'LKR', 'symbol' => '₨', 'is_default' => false],
        ['id' => 134, 'name' => 'Sudanese Pound', 'code' => 'SDG', 'symbol' => 'ج.س.', 'is_default' => false],
        ['id' => 135, 'name' => 'Surinamese Dollar', 'code' => 'SRD', 'symbol' => '$', 'is_default' => false],
        ['id' => 136, 'name' => 'Swazi Lilangeni', 'code' => 'SZL', 'symbol' => 'L', 'is_default' => false],
        ['id' => 137, 'name' => 'Syrian Pound', 'code' => 'SYP', 'symbol' => '£', 'is_default' => false],
        ['id' => 138, 'name' => 'Taiwanese New Dollar', 'code' => 'TWD', 'symbol' => 'NT$', 'is_default' => false],
        ['id' => 139, 'name' => 'Tajikistani Somoni', 'code' => 'TJS', 'symbol' => 'ЅМ', 'is_default' => false],
        ['id' => 140, 'name' => 'Tanzanian Shilling', 'code' => 'TZS', 'symbol' => 'Sh', 'is_default' => false],
        ['id' => 141, 'name' => 'Tongan Paʻanga', 'code' => 'TOP', 'symbol' => 'T$', 'is_default' => false],
        ['id' => 142, 'name' => 'Trinidad and Tobago Dollar', 'code' => 'TTD', 'symbol' => '$', 'is_default' => false],
        ['id' => 143, 'name' => 'Tunisian Dinar', 'code' => 'TND', 'symbol' => 'د.ت', 'is_default' => false],
        ['id' => 144, 'name' => 'Turkmenistani Manat', 'code' => 'TMT', 'symbol' => 'm', 'is_default' => false],
        ['id' => 145, 'name' => 'Ugandan Shilling', 'code' => 'UGX', 'symbol' => 'Sh', 'is_default' => false],
        ['id' => 146, 'name' => 'Ukrainian Hryvnia', 'code' => 'UAH', 'symbol' => '₴', 'is_default' => false],
        ['id' => 147, 'name' => 'Uruguayan Peso', 'code' => 'UYU', 'symbol' => '$', 'is_default' => false],
        ['id' => 148, 'name' => 'Uzbekistan Som', 'code' => 'UZS', 'symbol' => 'сўм', 'is_default' => false],
        ['id' => 149, 'name' => 'Vanuatu Vatu', 'code' => 'VUV', 'symbol' => 'Vt', 'is_default' => false],
        ['id' => 150, 'name' => 'Venezuelan Bolívar', 'code' => 'VES', 'symbol' => 'Bs.S.', 'is_default' => false],
        ['id' => 151, 'name' => 'Vietnamese Dong', 'code' => 'VND', 'symbol' => '₫', 'is_default' => false],
        ['id' => 152, 'name' => 'West African CFA Franc', 'code' => 'XOF', 'symbol' => 'Fr', 'is_default' => false],
        ['id' => 153, 'name' => 'Yemeni Rial', 'code' => 'YER', 'symbol' => '﷼', 'is_default' => false],
        ['id' => 154, 'name' => 'Zambian Kwacha', 'code' => 'ZMW', 'symbol' => 'ZK', 'is_default' => false],
        ['id' => 155, 'name' => 'Zimbabwean Dollar', 'code' => 'ZWL', 'symbol' => '$', 'is_default' => false],
    ]
];