<?php

return [
    'smtp' => [
        'name' => 'SMTP',
        'driver' => 'smtp',
        'host' => 'smtp.example.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'gmail' => [
        'name' => 'Gmail',
        'driver' => 'smtp',
        'host' => 'smtp.gmail.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'outlook' => [
        'name' => 'Outlook/Hotmail',
        'driver' => 'smtp',
        'host' => 'smtp-mail.outlook.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'yahoo' => [
        'name' => 'Yahoo Mail',
        'driver' => 'smtp',
        'host' => 'smtp.mail.yahoo.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'mailgun' => [
        'name' => 'Mailgun',
        'driver' => 'mailgun',
        'host' => 'smtp.mailgun.org',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'ses' => [
        'name' => 'Amazon SES',
        'driver' => 'ses',
        'host' => 'email-smtp.us-east-1.amazonaws.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'sendgrid' => [
        'name' => 'SendGrid',
        'driver' => 'smtp',
        'host' => 'smtp.sendgrid.net',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'postmark' => [
        'name' => 'Postmark',
        'driver' => 'smtp',
        'host' => 'smtp.postmarkapp.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'sparkpost' => [
        'name' => 'SparkPost',
        'driver' => 'smtp',
        'host' => 'smtp.sparkpostmail.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'mandrill' => [
        'name' => 'Mandrill',
        'driver' => 'smtp',
        'host' => 'smtp.mandrillapp.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'zoho' => [
        'name' => 'Zoho Mail',
        'driver' => 'smtp',
        'host' => 'smtp.zoho.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'mailjet' => [
        'name' => 'Mailjet',
        'driver' => 'smtp',
        'host' => 'in-v3.mailjet.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'elastic_email' => [
        'name' => 'Elastic Email',
        'driver' => 'smtp',
        'host' => 'smtp.elasticemail.com',
        'port' => '2525',
        'encryption' => 'tls',
    ],
    'smtp2go' => [
        'name' => 'SMTP2GO',
        'driver' => 'smtp',
        'host' => 'mail.smtp2go.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'socketlabs' => [
        'name' => 'SocketLabs',
        'driver' => 'smtp',
        'host' => 'smtp.socketlabs.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'pepipost' => [
        'name' => 'Pepipost',
        'driver' => 'smtp',
        'host' => 'smtp.pepipost.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'sendinblue' => [
        'name' => 'Sendinblue (Brevo)',
        'driver' => 'smtp',
        'host' => 'smtp-relay.sendinblue.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'mailchimp' => [
        'name' => 'Mailchimp Transactional',
        'driver' => 'smtp',
        'host' => 'smtp.mandrillapp.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'sendmail' => [
        'name' => 'Sendmail',
        'driver' => 'sendmail',
        'host' => '',
        'port' => '',
        'encryption' => 'none',
    ],
    'log' => [
        'name' => 'Log (Testing)',
        'driver' => 'log',
        'host' => '',
        'port' => '',
        'encryption' => 'none',
    ],
    'array' => [
        'name' => 'Array (Testing)',
        'driver' => 'array',
        'host' => '',
        'port' => '',
        'encryption' => 'none',
    ],
    'failover' => [
        'name' => 'Failover',
        'driver' => 'failover',
        'host' => '',
        'port' => '',
        'encryption' => 'none',
    ],
    'roundrobin' => [
        'name' => 'Round Robin',
        'driver' => 'roundrobin',
        'host' => '',
        'port' => '',
        'encryption' => 'none',
    ],
    'resend' => [
        'name' => 'Resend',
        'driver' => 'resend',
        'host' => 'smtp.resend.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'postmarkapp' => [
        'name' => 'PostmarkApp API',
        'driver' => 'postmark',
        'host' => '',
        'port' => '',
        'encryption' => 'none',
    ],
    'mailersend' => [
        'name' => 'MailerSend',
        'driver' => 'smtp',
        'host' => 'smtp.mailersend.net',
        'port' => '587',
        'encryption' => 'tls',
    ],
    'smtp_com' => [
        'name' => 'SMTP.com',
        'driver' => 'smtp',
        'host' => 'smtp.smtp.com',
        'port' => '587',
        'encryption' => 'tls',
    ],
];